#!/usr/bin/env python3

# script/test: Run test scripts.

from functions import (
    change_to_parent_directory,
    install_npm_dependencies,
    run_npm_test,
    install_composer_dependencies,
    run_composer_test,
    set_xdebug_mode
)

def main():
    change_to_parent_directory()
    install_composer_dependencies()
    set_xdebug_mode()
    run_composer_test()
    install_npm_dependencies()
    run_npm_test()

    print("==> All tests have been run successfully.")

if __name__ == "__main__":
    main()

